name:                jackal-server
version:             0.1.0.0
github:              "githubuser/jackal-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jackal-server#readme>

dependencies:
- base >= 4.7 && < 5
- bencode
- aeson
- async
- bytestring
- conduit
- containers
- cryptonite
- directory
- filepath
- ftp-client
- ftp-client-conduit
- haxr
- http-conduit
- jackal-api
- mtl
- rtorrent-rpc
- safe-exceptions
- servant-server
- stm
- vector
- warp
- wai

library:
  source-dirs: src
  exposed-modules:
    - Network.Jackal.Server
    - Network.Jackal.Server.Download
    - Network.Jackal.Server.Types
    - Network.Jackal.Server.Types.Config
    - Network.Jackal.Server.RTorrent

executables:
  jackal-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jackal-server

tests:
  jackal-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jackal-server
